src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $commentaire;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Pseudo;

    /**
     * @ORM\ManyToOne(targetEntity=Note::class, inversedBy="commentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity=Recette::class, inversedBy="commentaire")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recette;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getNote(): ?Note
    {
        return $this->note;
    }

    public function setNote(?Note $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getRecette(): ?Recette
    {
        return $this->recette;
    }

    public function setRecette(?Recette $recette): self
    {
        $this->recette = $recette;

        return $this;
    }
}

templates/cardTemplates/_descriptionCard.html.twig
<div class="card text-center">
    <div class="card-header">
        <p> Etape : {{ key + 1}}</p>
    </div>
    <div class="card-body">
        <p class="card-text">{{ r }}</p>
    </div>
</div>         

templates/cardTemplates/_indexCard.html.twig
    <div class="card" style="width: 20rem;">
    <img src="{{ asset('/upload/images/' ~ recette.image) }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">{{ recette.nomrecette }}</h5>   

            <p class="card-text">Noté : {{ recette.getMoyenneNote }}/5 ({{ recette.getTotalNote }})</p>
        </div>
        <ul class="list-group list-group-flush">
        
            <a class="list-group-item nav-link" href="{{ path('recette_show',{'id': recette.id}) }} ">Regarder la recette complète</a>
        </ul>
    </div>

templates/cardTemplates/_showCard.html.twig
 
    <div class="card col-lg-4" >
    <img src="{{ asset('/upload/images/' ~ recette.image) }}" class="card-img-top mt-3" alt="...">
        <div class="card-body">
            <h4 class="card-title">{{ recette.nomrecette }}</h4>   
            <p class="card-text">Pour : {{ recette.nombrepersonne }} personnes</p>
            <p class="card-text">Recette proposée par :  {{ recette.user.pseudo }}</p>
            <p class="card-text">Noté : {{ moyenne }}/5 ({{ totalNote }})</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Difficulté : {{ recette.difficulte.nomdifficulte }}</li>
            <li class="list-group-item">Prix : {{ recette.prix.nomprix }}</li>
            <li class="list-group-item">Temps : {{ recette.deserializer(recette.temps).hour }} h {{ recette.deserializer(recette.temps).minute }} min</li>
        </ul>
    </div>

templates/cardTemplates/_showCommentaire.html.twig
<div style="border:groove;border-radius:10px">
    <span> {{ commentAll.pseudo}}   {{ commentAll.note}}</span>
    <p>{{ commentAll.commentaire}}</p>
</div>